ci: fix ci yml
Signed-off-by: xiaoming <2014500726@smail.xtu.edu.cn>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -101,21 +101,6 @@ jobs:
           path: |
             toolchain.tar.gz
 
-      - name: Run tests uart update
-        shell: bash -l {0}
-        run: |
-          cd update_tools
-          conda create -n tools python=3.9.7 -y
-          conda activate tools
-          pip3 install -r requirements_pip.txt
-          cd ..
-          timeout --foreground -s SIGKILL 5m bash run.sh update_test > >(tee run_qemu.log) &
-          cd update_tools
-          sleep 1
-          timeout --foreground -s SIGKILL 5m python3 quard_star_tools.py > >(tee run_tools.log) || {
-            if cat run_tools.log | grep "update firmware done!" ; then echo "Pass simulation" && killall qemu-system-riscv64 && exit 0; else echo "Failed in update process" && exit 1; fi;
-          }
-
       - name: Run tests pflash boot
         shell: bash -l {0}
         run: |
@@ -142,3 +127,18 @@ jobs:
             if cat run_qemu.log | grep "Welcome debugging on Qemu Quard Star board!" ; then echo "Pass simulation" && killall qemu-system-riscv64 && exit 0; else echo "Failed in init process" && exit 1; fi;
           }
           rm run_qemu.log
+
+      - name: Run tests uart update
+        shell: bash -l {0}
+        run: |
+          cd update_tools
+          conda create -n tools python=3.9.7 -y
+          conda activate tools
+          pip3 install -r requirements_pip.txt
+          cd ..
+          timeout --foreground -s SIGKILL 5m bash run.sh update_test > >(tee run_qemu.log) &
+          cd update_tools
+          sleep 1
+          timeout --foreground -s SIGKILL 5m python3 quard_star_tools.py > >(tee run_tools.log) || {
+            if cat run_tools.log | grep "update firmware done!" ; then echo "Pass simulation" && killall qemu-system-riscv64 && exit 0; else echo "Failed in update process" && exit 1; fi;
+          }
