boot: add sd boot support in maskrom and lowlevelboot code
Signed-off-by: xiaoming <2014500726@smail.xtu.edu.cn>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -93,9 +93,23 @@ jobs:
           path: |
             toolchain.tar.gz
 
-      - name: Run tests
+      - name: Run tests pflash boot
         run: |
-          timeout --foreground -s SIGKILL 2m bash run.sh nographic > >(tee run_qemu.log) || {
+          timeout --foreground -s SIGKILL 5m bash run.sh nographic default pfalsh > >(tee run_qemu.log) || {
+            if cat run_qemu.log | grep "init process" ; then echo "Kernel boot successfully" ; else echo "Kernel boot failed" && exit 1; fi;
+            if cat run_qemu.log | grep "Welcome debugging on Qemu Quard Star board!" ; then echo "Pass simulation" && exit 0; else echo "Failed in init process" && exit 1; fi;
+          }
+
+      - name: Run tests spi boot
+        run: |
+          timeout --foreground -s SIGKILL 5m bash run.sh nographic default spi > >(tee run_qemu.log) || {
+            if cat run_qemu.log | grep "init process" ; then echo "Kernel boot successfully" ; else echo "Kernel boot failed" && exit 1; fi;
+            if cat run_qemu.log | grep "Welcome debugging on Qemu Quard Star board!" ; then echo "Pass simulation" && exit 0; else echo "Failed in init process" && exit 1; fi;
+          }
+
+      - name: Run tests sd boot
+        run: |
+          timeout --foreground -s SIGKILL 5m bash run.sh nographic default sd > >(tee run_qemu.log) || {
             if cat run_qemu.log | grep "init process" ; then echo "Kernel boot successfully" ; else echo "Kernel boot failed" && exit 1; fi;
             if cat run_qemu.log | grep "Welcome debugging on Qemu Quard Star board!" ; then echo "Pass simulation" && exit 0; else echo "Failed in init process" && exit 1; fi;
           }
