ci: update ci yml
Signed-off-by: xiaoming <2014500726@smail.xtu.edu.cn>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -102,29 +102,74 @@ jobs:
             toolchain.tar.gz
 
       - name: Run tests pflash boot
+        shell: bash -l {0}
         run: |
           timeout --foreground -s SIGKILL 5m bash run.sh nographic default pfalsh > >(tee run_qemu.log) || {
-            if cat run_qemu.log | grep "init process" ; then echo "Kernel boot successfully" ; else echo "Kernel boot failed" && exit 1; fi;
-            if cat run_qemu.log | grep "Welcome debugging on Qemu Quard Star board!" ; then echo "Pass simulation" && killall qemu-system-riscv64 && exit 0; else echo "Failed in init process" && exit 1; fi;
+            if cat run_qemu.log | grep "init process"
+            then
+              echo "Kernel boot successfully"
+            else
+              echo "Kernel boot failed"
+              killall qemu-system-riscv64 
+              exit 1
+            fi
+            if cat run_qemu.log | grep "Welcome debugging on Qemu Quard Star board!"
+            then
+              killall qemu-system-riscv64 
+              echo "Pass simulation" 
+            else
+              killall qemu-system-riscv64 
+              echo "Failed in init process"
+              exit 1
+            fi
           }
-          rm run_qemu.log
 
       - name: Run tests spi boot
+        shell: bash -l {0}
         run: |
           timeout --foreground -s SIGKILL 5m bash run.sh nographic default spi > >(tee run_qemu.log) || {
-            if cat run_qemu.log | grep "init process" ; then echo "Kernel boot successfully" ; else echo "Kernel boot failed" && exit 1; fi;
-            if cat run_qemu.log | grep "Welcome debugging on Qemu Quard Star board!" ; then echo "Pass simulation" && killall qemu-system-riscv64 && exit 0; else echo "Failed in init process" && exit 1; fi;
+            if cat run_qemu.log | grep "init process"
+            then
+              echo "Kernel boot successfully"
+            else
+              echo "Kernel boot failed"
+              killall qemu-system-riscv64 
+              exit 1
+            fi
+            if cat run_qemu.log | grep "Welcome debugging on Qemu Quard Star board!"
+            then
+              killall qemu-system-riscv64 
+              echo "Pass simulation" 
+            else
+              killall qemu-system-riscv64 
+              echo "Failed in init process"
+              exit 1
+            fi
           }
-          rm run_qemu.log
 
       - name: Run tests sd boot
+        shell: bash -l {0}
         run: |
           timeout --foreground -s SIGKILL 5m bash run.sh nographic default sd > >(tee run_qemu.log) || {
-            if cat run_qemu.log | grep "init process" ; then echo "Kernel boot successfully" ; else echo "Kernel boot failed" && exit 1; fi;
-            if cat run_qemu.log | grep "Welcome debugging on Qemu Quard Star board!" ; then echo "Pass simulation" && killall qemu-system-riscv64 && exit 0; else echo "Failed in init process" && exit 1; fi;
+            if cat run_qemu.log | grep "init process"
+            then
+              echo "Kernel boot successfully"
+            else
+              echo "Kernel boot failed"
+              killall qemu-system-riscv64 
+              exit 1
+            fi
+            if cat run_qemu.log | grep "Welcome debugging on Qemu Quard Star board!"
+            then
+              killall qemu-system-riscv64 
+              echo "Pass simulation" 
+            else
+              killall qemu-system-riscv64 
+              echo "Failed in init process"
+              exit 1
+            fi
           }
-          rm run_qemu.log
-
+          
       - name: Run tests uart update
         shell: bash -l {0}
         run: |
@@ -135,5 +180,15 @@ jobs:
           cd ..
           timeout --foreground -s SIGKILL 5m bash run.sh update_test > >(tee run_qemu.log) &
           cd update_tools
-          sleep 1
-          timeout --foreground -s SIGKILL 5m python3 quard_star_tools.py
+          sleep 5
+          timeout --foreground -s SIGKILL 5m python3 quard_star_tools.py > >(tee run_tools.log) && {
+            if cat run_tools.log | grep "update firmware done"
+            then
+              killall qemu-system-riscv64 
+              echo "Pass simulation"
+            else
+              killall qemu-system-riscv64 
+              echo "Failed in updater process"
+              exit 1
+            fi
+          }
